### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by brhea** [ThadHouse/CmakeWpilib#5]
I've tried building this and received errors:
I'm trying to build on windows 10... eventually crosscompiling on windows for raspberry pi.
CMake never creates a "Make" file.

CMake Deprecation Warning at C:/Program Files/CMake/share/cmake-3.11/Modules/UseJava.cmake:1318 (message):
  create_javah: this command will no longer be supported starting with
  version 10 of JDK.  Update your project by using command
  add_jar(GENERATE_NATIVE_HEADERS) instead.
Call Stack (most recent call first):
  libraries/allwpilib/CMakeLists.txt:88 (create_javah)

-- Configuring done
CMake Error at libraries/wpiutil/CMakeLists.txt:26 (add_library):
  No SOURCES given to target: wpiutil

CMake Error at libraries/ntcore/CMakeLists.txt:37 (add_library):
  No SOURCES given to target: ntcore

CMake Error at libraries/allwpilib/CMakeLists.txt:12 (add_library):
  No SOURCES given to target: wpiHal

CMake Error at libraries/allwpilib/CMakeLists.txt:93 (add_library):
  No SOURCES given to target: wpilibJNI

**Comment by ThadHouse** [comment]
That issue is you don't have the submodules cloned. But this repo is no longer maintained, and it's functionality has been moved into the main allwpilib repo.

Note that cross compiling is not a supported configuration in the setup in allwpilib. You can probably get it set up and working, but it's never been tested and is going to require some cmake knowledge to get working. We recommend compiling directly on the device. Also windows is even more difficult in that setup, and if you want to attempt to cross compile you will likely need Linux.
